version: '3.1'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      SPRING_DATA_MONGODB_URI:  mongodb://root:cafezim@mongo:27017/mongo_db?authSource=admin
    ports:
      - 8080:8080
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: mongo_db
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: cafezim
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: cafezim
      ME_CONFIG_MONGODB_URL: mongodb://root:cafezim@mongo:27017/



